// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop_service.proto

package stubs;

public interface ImageInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImageInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string laptop_id = 1;</code>
   * @return The laptopId.
   */
  java.lang.String getLaptopId();
  /**
   * <code>string laptop_id = 1;</code>
   * @return The bytes for laptopId.
   */
  com.google.protobuf.ByteString
      getLaptopIdBytes();

  /**
   * <code>string image_type = 2;</code>
   * @return The imageType.
   */
  java.lang.String getImageType();
  /**
   * <code>string image_type = 2;</code>
   * @return The bytes for imageType.
   */
  com.google.protobuf.ByteString
      getImageTypeBytes();
}
