// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keyboard_message.proto

package stubs;

public final class KeyboardMessage {
  private KeyboardMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Keyboard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Keyboard_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026keyboard_message.proto\"y\n\010Keyboard\022 \n\006" +
      "layout\030\001 \001(\0162\020.Keyboard.Layout\022\020\n\010blackl" +
      "it\030\002 \001(\010\"9\n\006Layout\022\013\n\007UNKNOWN\020\000\022\n\n\006QWERT" +
      "Y\020\001\022\n\n\006QWERTZ\020\002\022\n\n\006AZERTY\020\003B\t\n\005stubsP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Keyboard_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Keyboard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Keyboard_descriptor,
        new java.lang.String[] { "Layout", "Blacklit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
