// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keyboard_message.proto

package stubs;

public interface KeyboardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Keyboard)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Keyboard.Layout layout = 1;</code>
   * @return The enum numeric value on the wire for layout.
   */
  int getLayoutValue();
  /**
   * <code>.Keyboard.Layout layout = 1;</code>
   * @return The layout.
   */
  stubs.Keyboard.Layout getLayout();

  /**
   * <code>bool blacklit = 2;</code>
   * @return The blacklit.
   */
  boolean getBlacklit();
}
