// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop_service.proto

package stubs;

public final class LaptopServiceOuterClass {
  private LaptopServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateLaptopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateLaptopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateLaptopResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateLaptopResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchLaptopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchLaptopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchLaptopResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchLaptopResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadImageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadImageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadImageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadImageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RateLaptopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RateLaptopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RateLaptopResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RateLaptopResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024laptop_service.proto\032\024laptop_message.p" +
      "roto\032\024filter_message.proto\".\n\023CreateLapt" +
      "opRequest\022\027\n\006laptop\030\001 \001(\0132\007.Laptop\"\"\n\024Cr" +
      "eateLaptopResponse\022\n\n\002id\030\001 \001(\t\".\n\023Search" +
      "LaptopRequest\022\027\n\006filter\030\001 \001(\0132\007.Filter\"/" +
      "\n\024SearchLaptopResponse\022\027\n\006laptop\030\001 \001(\0132\007" +
      ".Laptop\"N\n\022UploadImageRequest\022\032\n\004info\030\001 " +
      "\001(\0132\n.ImageInfoH\000\022\024\n\nchunk_data\030\002 \001(\014H\000B" +
      "\006\n\004data\"2\n\tImageInfo\022\021\n\tlaptop_id\030\001 \001(\t\022" +
      "\022\n\nimage_type\030\002 \001(\t\"/\n\023UploadImageRespon" +
      "se\022\n\n\002id\030\001 \001(\t\022\014\n\004size\030\002 \001(\r\"5\n\021RateLapt" +
      "opRequest\022\021\n\tlaptop_id\030\001 \001(\t\022\r\n\005score\030\002 " +
      "\001(\001\"S\n\022RateLaptopResponse\022\021\n\tlaptop_id\030\001" +
      " \001(\t\022\023\n\013rated_count\030\002 \001(\r\022\025\n\raverage_sco" +
      "re\030\003 \001(\0012\212\002\n\rLaptopService\022=\n\014CreateLapt" +
      "op\022\024.CreateLaptopRequest\032\025.CreateLaptopR" +
      "esponse\"\000\022?\n\014SearchLaptop\022\024.SearchLaptop" +
      "Request\032\025.SearchLaptopResponse\"\0000\001\022<\n\013Up" +
      "loadImage\022\023.UploadImageRequest\032\024.UploadI" +
      "mageResponse\"\000(\001\022;\n\nRateLaptop\022\022.RateLap" +
      "topRequest\032\023.RateLaptopResponse\"\000(\0010\001B\t\n" +
      "\005stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          stubs.LaptopMessage.getDescriptor(),
          stubs.FilterMessage.getDescriptor(),
        });
    internal_static_CreateLaptopRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateLaptopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateLaptopRequest_descriptor,
        new java.lang.String[] { "Laptop", });
    internal_static_CreateLaptopResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreateLaptopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateLaptopResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_SearchLaptopRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SearchLaptopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchLaptopRequest_descriptor,
        new java.lang.String[] { "Filter", });
    internal_static_SearchLaptopResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SearchLaptopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchLaptopResponse_descriptor,
        new java.lang.String[] { "Laptop", });
    internal_static_UploadImageRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UploadImageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadImageRequest_descriptor,
        new java.lang.String[] { "Info", "ChunkData", "Data", });
    internal_static_ImageInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ImageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageInfo_descriptor,
        new java.lang.String[] { "LaptopId", "ImageType", });
    internal_static_UploadImageResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_UploadImageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadImageResponse_descriptor,
        new java.lang.String[] { "Id", "Size", });
    internal_static_RateLaptopRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_RateLaptopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RateLaptopRequest_descriptor,
        new java.lang.String[] { "LaptopId", "Score", });
    internal_static_RateLaptopResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_RateLaptopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RateLaptopResponse_descriptor,
        new java.lang.String[] { "LaptopId", "RatedCount", "AverageScore", });
    stubs.LaptopMessage.getDescriptor();
    stubs.FilterMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
