// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop_service.proto

package stubs;

public interface SearchLaptopRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchLaptopRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Filter filter = 1;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>.Filter filter = 1;</code>
   * @return The filter.
   */
  stubs.Filter getFilter();
  /**
   * <code>.Filter filter = 1;</code>
   */
  stubs.FilterOrBuilder getFilterOrBuilder();
}
