// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop_service.proto

package stubs;

public interface SearchLaptopResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchLaptopResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Laptop laptop = 1;</code>
   * @return Whether the laptop field is set.
   */
  boolean hasLaptop();
  /**
   * <code>.Laptop laptop = 1;</code>
   * @return The laptop.
   */
  stubs.Laptop getLaptop();
  /**
   * <code>.Laptop laptop = 1;</code>
   */
  stubs.LaptopOrBuilder getLaptopOrBuilder();
}
