// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_message.proto

package stubs;

public interface StorageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Storage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Storage.Driver driver = 1;</code>
   * @return The enum numeric value on the wire for driver.
   */
  int getDriverValue();
  /**
   * <code>.Storage.Driver driver = 1;</code>
   * @return The driver.
   */
  stubs.Storage.Driver getDriver();

  /**
   * <code>.Memory memory = 2;</code>
   * @return Whether the memory field is set.
   */
  boolean hasMemory();
  /**
   * <code>.Memory memory = 2;</code>
   * @return The memory.
   */
  stubs.Memory getMemory();
  /**
   * <code>.Memory memory = 2;</code>
   */
  stubs.MemoryOrBuilder getMemoryOrBuilder();
}
