// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop_service.proto

package stubs;

public interface UploadImageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UploadImageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImageInfo info = 1;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.ImageInfo info = 1;</code>
   * @return The info.
   */
  stubs.ImageInfo getInfo();
  /**
   * <code>.ImageInfo info = 1;</code>
   */
  stubs.ImageInfoOrBuilder getInfoOrBuilder();

  /**
   * <code>bytes chunk_data = 2;</code>
   * @return The chunkData.
   */
  com.google.protobuf.ByteString getChunkData();

  public stubs.UploadImageRequest.DataCase getDataCase();
}
